---
title: "1 Tag Früher"
description: |
  Freiwillige Menschenversuche zu Testung von Corona Impfstoffen
site: distill::distill_website
bibliography: biblio.bib
---
**Bei sogenannten 'Human Challenge Trials' werden Teilnehmer bewusst mit dem Virus angesteckt, um eine Impfung testen zu können.
Dies kann die Zeit, die zur Entwicklung massiv beschleunigen.**

**Aus ethischen Gründen, ist dies normalerweise nicht vorgesehen.
Ich (und auch führende Wissenschafter [@eyal]) denken aber, dass es aber in dieser Situation durchaus sinnvoll ist, mögliche Impfstoffe gegen das Corona Virus, derart zu Testen.**

### Wie Menschenversuche helfen, die Entwicklung eines Impfstoffen zu beschleunigen.
Gewöhnlich kann es Jahre dauern, bis ein Impfstoff Genehmigt wird.
Dabei ist es nicht die eigentliche Suche nach dem neuen Impfstoff, die diesen Prozess so langwierig macht, sondern die Menschenversuche.
Dabei wird der Impfstoff in 3 Phasen immer mehr Personen Verabreicht.
In Phase 3 werden mehreren tausen Personen geimpft.
Um dann zu zeigen, dass der Impfstoff effektiv ist, wird mehrere Monate gewartet, und die Infektionsraten unter den geimpften mit einer Kontrollgruppe zu vergleichen.
Die kann aber mehrere Monate dauern, und mit den derzeitigen social-distancing Maßnahmen, kann es sehr lange dauern, bis diese Versuche ein statistisch signifikantes Ergebnis liefern. 


